# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lyXSu06z14MKsLJS0LZmEVRnh7U5Hrz
"""

import re
from collections import Counter

def build_vocab(questions, min_freq=1):
    counter = Counter()
    for q in questions:
        tokens = re.findall(r"\w+|[^\w\s]", str(q).lower(), re.UNICODE)
        counter.update(tokens)
    vocab = {'<pad>': 0, '<start>': 1, '<end>': 2, '<unk>': 3}
    idx = 4
    for word, freq in counter.items():
        if freq >= min_freq:
            vocab[word] = idx
            idx += 1
    return vocab, {i: w for w, i in vocab.items()}